# JAX 错误

> 原文：[`jax.readthedocs.io/en/latest/errors.html`](https://jax.readthedocs.io/en/latest/errors.html)

此页面列出了在使用 JAX 时可能遇到的一些错误，以及如何修复它们的代表性示例。

```py
class jax.errors.ConcretizationTypeError(tracer, context='')
```

当 JAX 追踪器对象在需要具体值的上下文中使用时（参见关于 Tracer 是什么的更多信息），会发生此错误。在某些情况下，可以通过将问题值标记为静态来轻松修复；在其他情况下，可能表明您的程序正在执行 JAX JIT 编译模型不直接支持的操作。

例子：

在期望静态值的位置使用跟踪值

导致此错误的一个常见原因是在需要静态值的位置使用跟踪值。例如：

```py
>>> from functools import partial
>>> from jax import jit
>>> import jax.numpy as jnp
>>> @jit
... def func(x, axis):
...   return x.min(axis) 
```

```py
>>> func(jnp.arange(4), 0)  
Traceback (most recent call last):
  ...
ConcretizationTypeError: Abstract tracer value encountered where concrete
value is expected: axis argument to jnp.min(). 
```

通常可以通过将问题参数标记为静态来解决此问题：

```py
>>> @partial(jit, static_argnums=1)
... def func(x, axis):
...   return x.min(axis)

>>> func(jnp.arange(4), 0)
Array(0, dtype=int32) 
```

形状依赖于跟踪的值

在 JIT 编译的计算中，如果形状依赖于跟踪数量中的值时，也可能出现此类错误。例如：

```py
>>> @jit
... def func(x):
...     return jnp.where(x < 0)

>>> func(jnp.arange(4))  
Traceback (most recent call last):
  ...
ConcretizationTypeError: Abstract tracer value encountered where concrete value is expected:
The error arose in jnp.nonzero. 
```

这是一个与 JAX JIT 编译模型不兼容的操作示例，该模型要求在编译时知道数组大小。这里返回的数组大小取决于 x 的内容，这样的代码不能 JIT 编译。

在许多情况下，可以通过修改函数中使用的逻辑来解决此问题；例如，这里是一个类似问题的代码：

```py
>>> @jit
... def func(x):
...     indices = jnp.where(x > 1)
...     return x[indices].sum()

>>> func(jnp.arange(4))  
Traceback (most recent call last):
  ...
ConcretizationTypeError: Abstract tracer value encountered where concrete
value is expected: The error arose in jnp.nonzero. 
```

以下是如何以避免创建动态大小索引数组的方式表达相同操作的示例：

```py
>>> @jit
... def func(x):
...   return jnp.where(x > 1, x, 0).sum()

>>> func(jnp.arange(4))
Array(5, dtype=int32) 
```

要了解与跟踪器与常规值，具体与抽象值相关的更多细微差别，可以阅读有关不同类型的 JAX 值的内容。

参数：

+   **追踪器** (*core.Tracer*)

+   **上下文** ([*str*](https://docs.python.org/3/library/stdtypes.html#str "(在 Python v3.12 中)"))

```py
class jax.errors.KeyReuseError(message)
```

当 PRNG 密钥以不安全的方式重复使用时，会发生此错误。仅在设置 `jax_debug_key_reuse` 为 True 时检查密钥重复使用。

以下是导致此类错误的代码简单示例：

```py
>>> with jax.debug_key_reuse(True):  
...   key = jax.random.key(0)
...   value = jax.random.uniform(key)
...   new_value = jax.random.uniform(key)
...
---------------------------------------------------------------------------
KeyReuseError                             Traceback (most recent call last)
...
KeyReuseError: Previously-consumed key passed to jit-compiled function at index 0 
```

此类密钥重用存在问题，因为 JAX PRNG 是无状态的，必须手动分割密钥；有关更多信息，请参见 [Sharp Bits: Random Numbers](https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html#random-numbers)。

参数：

**消息** ([*str*](https://docs.python.org/3/library/stdtypes.html#str "(在 Python v3.12 中)"))

```py
class jax.errors.NonConcreteBooleanIndexError(tracer)
```

当程序尝试在跟踪索引操作中使用非具体布尔索引时，会发生此错误。在 JIT 编译下，JAX 数组必须具有静态形状（即在编译时已知的形状），因此布尔掩码必须小心使用。某些逻辑通过布尔掩码实现可能在 `jax.jit()` 函数中根本不可能；在其他情况下，可以使用 `where()` 的三参数版本以 JIT 兼容的方式重新表达逻辑。

以下是可能导致此错误的几个示例。

通过布尔掩码构建数组

在尝试在 JIT 上下文中通过布尔遮罩创建数组时最常见出现此错误。例如：

```py
>>> import jax
>>> import jax.numpy as jnp

>>> @jax.jit
... def positive_values(x):
...   return x[x > 0]

>>> positive_values(jnp.arange(-5, 5))  
Traceback (most recent call last):
  ...
NonConcreteBooleanIndexError: Array boolean indices must be concrete: ShapedArray(bool[10]) 
```

此函数试图仅返回输入数组中的正值；除非将 x 标记为静态，否则在编译时无法确定返回数组的大小，因此无法在 JIT 编译下执行此类操作。

可重新表达的布尔逻辑

尽管不直接支持创建动态大小的数组，但在许多情况下可以重新表达计算逻辑以符合 JIT 兼容的操作。例如，以下是另一个因相同原因在 JIT 下失败的函数：

```py
>>> @jax.jit
... def sum_of_positive(x):
...   return x[x > 0].sum()

>>> sum_of_positive(jnp.arange(-5, 5))  
Traceback (most recent call last):
  ...
NonConcreteBooleanIndexError: Array boolean indices must be concrete: ShapedArray(bool[10]) 
```

然而，在这种情况下，有问题的数组仅是一个中间值，我们可以使用支持 JIT 的三参数版本的 `jax.numpy.where()` 表达相同的逻辑：

```py
>>> @jax.jit
... def sum_of_positive(x):
...   return jnp.where(x > 0, x, 0).sum()

>>> sum_of_positive(jnp.arange(-5, 5))
Array(10, dtype=int32) 
```

将布尔遮罩替换为带有三个参数的 `where()` 的模式是解决这类问题的常见方法。

对 JAX 数组进行布尔索引

另一个经常出现此错误的情况是使用布尔索引，例如 `.at[...].set(...)`。以下是一个简单的示例：

```py
>>> @jax.jit
... def manual_clip(x):
...   return x.at[x < 0].set(0)

>>> manual_clip(jnp.arange(-2, 2))  
Traceback (most recent call last):
  ...
NonConcreteBooleanIndexError: Array boolean indices must be concrete: ShapedArray(bool[4]) 
```

此函数试图将小于零的值设置为标量填充值。与上述类似，可以通过在 `where()` 中重新表达逻辑来解决此问题：

```py
>>> @jax.jit
... def manual_clip(x):
...   return jnp.where(x < 0, 0, x)

>>> manual_clip(jnp.arange(-2, 2))
Array([0, 0, 0, 1], dtype=int32) 
```

参数：

**tracer** (*core.Tracer*)

```py
class jax.errors.TracerArrayConversionError(tracer)
```

当程序尝试将 JAX 追踪对象转换为标准的 NumPy 数组时会发生此错误（详见不同类型的 JAX 值，了解追踪器的更多信息）。通常情况下会发生在几种情况之一。

在 JAX 变换中使用非 JAX 函数

如果尝试在 JAX 变换（`jit()`、`grad()`、`jax.vmap()` 等）内部使用非 JAX 库如 `numpy` 或 `scipy`，则可能会导致此错误。例如：

```py
>>> from jax import jit
>>> import numpy as np

>>> @jit
... def func(x):
...   return np.sin(x)

>>> func(np.arange(4))  
Traceback (most recent call last):
  ...
TracerArrayConversionError: The numpy.ndarray conversion method
__array__() was called on traced array with shape int32[4] 
```

在这种情况下，你可以通过使用 `jax.numpy.sin()` 替换 `numpy.sin()` 来解决问题：

```py
>>> import jax.numpy as jnp
>>> @jit
... def func(x):
...   return jnp.sin(x)

>>> func(jnp.arange(4))
Array([0\.        , 0.84147096, 0.9092974 , 0.14112   ], dtype=float32) 
```

另请参阅 [External Callbacks](https://jax.readthedocs.io/en/latest/notebooks/external_callbacks.html) 了解从转换的 JAX 代码返回到主机端计算的选项。

使用追踪器索引 numpy 数组

如果此错误出现在涉及数组索引的行上，则可能是被索引的数组 `x` 是标准的 numpy.ndarray，而索引 `idx` 是追踪的 JAX 数组。例如：

```py
>>> x = np.arange(10)

>>> @jit
... def func(i):
...   return x[i]

>>> func(0)  
Traceback (most recent call last):
  ...
TracerArrayConversionError: The numpy.ndarray conversion method
__array__() was called on traced array with shape int32[0] 
```

根据上下文，你可以通过将 numpy 数组转换为 JAX 数组来解决此问题：

```py
>>> @jit
... def func(i):
...   return jnp.asarray(x)[i]

>>> func(0)
Array(0, dtype=int32) 
```

或者通过将索引声明为静态参数：

```py
>>> from functools import partial
>>> @partial(jit, static_argnums=(0,))
... def func(i):
...   return x[i]

>>> func(0)
Array(0, dtype=int32) 
```

要了解关于追踪器与常规值、具体值与抽象值的更多微妙之处，可以阅读有关不同类型的 JAX 值。

参数：

**tracer** (*core.Tracer*)

```py
class jax.errors.TracerBoolConversionError(tracer)
```

当在期望布尔值的上下文中使用 JAX 中的追踪值时会出现此错误（详见不同类型的 JAX 值，了解追踪器的更多信息）。

布尔转换可以是显式的（例如`bool(x)`）或隐式的，通过控制流的使用（例如`if x > 0`或`while x`）、使用 Python 布尔运算符（例如`z = x and y`、`z = x or y`、`z = not x`）或使用它们的函数（例如`z = max(x, y)`、`z = min(x, y)`等）。

在某些情况下，通过将跟踪值标记为静态，可以轻松解决此问题；在其他情况下，这可能表明您的程序正在执行 JAX JIT 编译模型不直接支持的操作。

示例：

在控制流中使用跟踪值

一个经常出现这种情况的案例是，当跟踪值用于 Python 控制流时。例如：

```py
>>> from jax import jit
>>> import jax.numpy as jnp
>>> @jit
... def func(x, y):
...   return x if x.sum() < y.sum() else y

>>> func(jnp.ones(4), jnp.zeros(4))  
Traceback (most recent call last):
  ...
TracerBoolConversionError: Attempted boolean conversion of JAX Tracer [...] 
```

我们可以将输入的`x`和`y`都标记为静态，但这样做将破坏在这里使用`jax.jit()`的目的。另一个选择是将 if 语句重新表达为三项`jax.numpy.where()`：

```py
>>> @jit
... def func(x, y):
...   return jnp.where(x.sum() < y.sum(), x, y)

>>> func(jnp.ones(4), jnp.zeros(4))
Array([0., 0., 0., 0.], dtype=float32) 
```

对于包括循环在内的更复杂的控制流，请参阅控制流运算符。

跟踪值在控制流中的使用

另一个常见的错误原因是，如果您无意中在布尔标志上进行跟踪。例如：

```py
>>> @jit
... def func(x, normalize=True):
...   if normalize:
...     return x / x.sum()
...   return x

>>> func(jnp.arange(5), True)  
Traceback (most recent call last):
  ...
TracerBoolConversionError: Attempted boolean conversion of JAX Tracer ... 
```

在这里，因为标志`normalize`被跟踪，所以不能在 Python 控制流中使用它。在这种情况下，最好的解决方案可能是将此值标记为静态：

```py
>>> from functools import partial
>>> @partial(jit, static_argnames=['normalize'])
... def func(x, normalize=True):
...   if normalize:
...     return x / x.sum()
...   return x

>>> func(jnp.arange(5), True)
Array([0\. , 0.1, 0.2, 0.3, 0.4], dtype=float32) 
```

有关`static_argnums`的更多信息，请参阅`jax.jit()`的文档。

使用非 JAX 感知的函数

另一个常见的错误原因是在 JAX 代码中使用非 JAX 感知的函数。例如：

```py
>>> @jit
... def func(x):
...   return min(x, 0) 
```

```py
>>> func(2)  
Traceback (most recent call last):
  ...
TracerBoolConversionError: Attempted boolean conversion of JAX Tracer ... 
```

在这种情况下，错误是因为 Python 的内置`min`函数与 JAX 变换不兼容。可以通过将其替换为`jnp.minimum`来修复这个问题：

```py
>>> @jit
... def func(x):
...   return jnp.minimum(x, 0) 
```

```py
>>> print(func(2))
0 
```

要更深入了解关于跟踪器与常规值、具体值与抽象值之间的微妙差别，您可能需要阅读关于不同类型 JAX 值的文档。

参数：

**tracer**（*core.Tracer*）

```py
class jax.errors.TracerIntegerConversionError(tracer)
```

如果在期望 Python 整数的上下文中使用 JAX Tracer 对象，则可能会出现此错误（有关 Tracer 是什么的更多信息，请参阅关于不同类型 JAX 值的内容）。它通常发生在几种情况下。

将跟踪器放在整数位置

如果您试图将跟踪值传递给需要静态整数参数的函数，则可能会出现此错误；例如：

```py
>>> from jax import jit
>>> import numpy as np

>>> @jit
... def func(x, axis):
...   return np.split(x, 2, axis)

>>> func(np.arange(4), 0)  
Traceback (most recent call last):
  ...
TracerIntegerConversionError: The __index__() method was called on
traced array with shape int32[0] 
```

当出现这种情况时，解决方案通常是将有问题的参数标记为静态：

```py
>>> from functools import partial
>>> @partial(jit, static_argnums=1)
... def func(x, axis):
...   return np.split(x, 2, axis)

>>> func(np.arange(10), 0)
[Array([0, 1, 2, 3, 4], dtype=int32),
 Array([5, 6, 7, 8, 9], dtype=int32)] 
```

另一种方法是将转换应用于封装要保护参数的闭包，可以手动执行如下或使用[`functools.partial()`](https://docs.python.org/3/library/functools.html#functools.partial "（在 Python v3.12 中）")：

```py
>>> jit(lambda arr: np.split(arr, 2, 0))(np.arange(4))
[Array([0, 1], dtype=int32), Array([2, 3], dtype=int32)] 
```

**请注意，每次调用都会创建一个新的闭包，这会破坏编译缓存机制，这也是为什么首选`static_argnums`的原因。**

使用跟踪器索引列表

如果您尝试使用跟踪的量索引 Python 列表，则可能会出现此错误。例如：

```py
>>> import jax.numpy as jnp
>>> from jax import jit

>>> L = [1, 2, 3]

>>> @jit
... def func(i):
...   return L[i]

>>> func(0)  
Traceback (most recent call last):
  ...
TracerIntegerConversionError: The __index__() method was called on
traced array with shape int32[0] 
```

根据上下文，通常可以通过将列表转换为 JAX 数组来解决此问题：

```py
>>> @jit
... def func(i):
...   return jnp.array(L)[i]

>>> func(0)
Array(1, dtype=int32) 
```

或者通过将索引声明为静态参数来声明：

```py
>>> from functools import partial
>>> @partial(jit, static_argnums=0)
... def func(i):
...   return L[i]

>>> func(0)
Array(1, dtype=int32, weak_type=True) 
```

要更深入理解跟踪器与常规值以及具体与抽象值之间的微妙差别，您可以阅读有关不同类型 JAX 值的文档。

参数：

**tracer**（*core.Tracer*）

```py
class jax.errors.UnexpectedTracerError(msg)
```

当您使用从函数中泄漏出来的 JAX 值时，会出现此错误。泄漏值是什么意思？如果您对函数`f`应用 JAX 转换，并在`f`外某个作用域存储了一个中间值的引用，那么该值被视为已泄漏。泄漏值是副作用。（阅读更多关于避免副作用的内容，请参阅[Pure Functions](https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html#pure-functions)）

JAX 在你稍后在另一个操作中使用泄露的值时检测到泄漏，此时会引发`UnexpectedTracerError`。要修复此问题，请避免副作用：如果一个函数计算了外部作用域需要的值，则需要明确从转换后的函数中返回该值。

具体来说，`Tracer`是 JAX 在转换期间函数中间值的内部表示，例如在`jit()`、`pmap()`、`vmap()`等内部。在转换之外遇到`Tracer`表示泄漏。

泄漏值的生命周期

请考虑以下转换函数的示例，它将一个值泄漏到外部作用域：

```py
>>> from jax import jit
>>> import jax.numpy as jnp

>>> outs = []
>>> @jit                   # 1
... def side_effecting(x):
...   y = x + 1            # 3
...   outs.append(y)       # 4

>>> x = 1
>>> side_effecting(x)      # 2
>>> outs[0] + 1            # 5 
Traceback (most recent call last):
  ...
UnexpectedTracerError: Encountered an unexpected tracer. 
```

在此示例中，我们从内部转换作用域泄漏了一个跟踪值到外部作用域。当使用泄漏值而不是泄漏值时，会出现`UnexpectedTracerError`。

此示例还展示了泄漏值的生命周期：

> 1.  函数被转换了（在本例中，通过`jit()`）。
> 1.  
> 1.  调用了转换后的函数（启动函数的抽象跟踪，并将`x`转换为`Tracer`）。
> 1.  
> 1.  中间值`y`被创建，稍后将被泄漏（跟踪函数的中间值也是`Tracer`）。
> 1.  
> 1.  该值已泄漏（通过外部作用域的一个侧通道将其追加到列表中逃逸函数）
> 1.  
> 1.  使用了泄漏的值，并引发了 UnexpectedTracerError。

UnexpectedTracerError 消息试图通过包含有关每个阶段信息的方法来指出代码中的这些位置。依次：

> 1.  转换后函数的名称（`side_effecting`）以及触发跟踪的转换名称`jit()`）。
> 1.  
> 1.  泄漏的 Tracer 创建时的重构堆栈跟踪，包括调用转换后函数的位置。（`When the Tracer was created, the final 5 stack frames were...`）。
> 1.  
> 1.  从重构的堆栈跟踪中，创建泄漏 Tracer 的代码行。
> 1.  
> 1.  错误消息中不包括泄漏位置，因为难以确定！JAX 只能告诉你泄漏值的外观（其形状和创建位置）以及泄漏的边界（变换的名称和转换后函数的名称）。
> 1.  
> 1.  当前错误的堆栈跟踪指向值的使用位置。

可以通过将值从转换函数返回来修复错误：

```py
>>> from jax import jit
>>> import jax.numpy as jnp

>>> outs = []
>>> @jit
... def not_side_effecting(x):
...   y = x+1
...   return y

>>> x = 1
>>> y = not_side_effecting(x)
>>> outs.append(y)
>>> outs[0] + 1  # all good! no longer a leaked value.
Array(3, dtype=int32, weak_type=True) 
```

泄漏检查器

如上述第 2 和第 3 点所讨论的那样，JAX 显示了一个重建的堆栈跟踪，指出了泄露值的创建位置。这是因为 JAX 仅在使用泄露值时才会引发错误，而不是在值泄漏时。这不是引发此错误的最有用的地方，因为您需要知道泄露跟踪器的位置来修复错误。

为了更容易跟踪此位置，您可以使用泄漏检查器。当启用泄漏检查器时，一旦泄露了`Tracer`，就会引发错误。（更确切地说，在从中泄漏`Tracer`的转换函数返回时会引发错误）

要启用泄漏检查器，可以使用`JAX_CHECK_TRACER_LEAKS`环境变量或`with jax.checking_leaks()`上下文管理器。

注意

请注意，此工具属于实验性质，可能会报告错误的情况。它通过禁用某些 JAX 缓存工作，因此会对性能产生负面影响，应仅在调试时使用。

示例用法：

```py
>>> from jax import jit
>>> import jax.numpy as jnp

>>> outs = []
>>> @jit
... def side_effecting(x):
...   y = x+1
...   outs.append(y)

>>> x = 1
>>> with jax.checking_leaks():
...   y = side_effecting(x)  
Traceback (most recent call last):
  ...
Exception: Leaked Trace 
```

参数：

**msg** ([*str*](https://docs.python.org/3/library/stdtypes.html#str "(在 Python v3.12 中)"))
