["```py\nwith jax.profiler.trace(\"/tmp/jax-trace\", create_perfetto_link=True):\n  # Run the operations to be profiled\n  key = jax.random.key(0)\n  x = jax.random.normal(key, (5000, 5000))\n  y = x @ x\n  y.block_until_ready() \n```", "```py\n$  ssh  -L  9001:127.0.0.1:9001  <user>@<host> \n```", "```py\n$  gcloud  compute  ssh  <machine-name>  --  -L  9001:127.0.0.1:9001 \n```", "```py\n$  python  -m  jax.collect_profile  <port>  <duration_in_ms> \n```", "```py\npip  install  tensorflow  tensorboard-plugin-profile \n```", "```py\nimport jax\n\njax.profiler.start_trace(\"/tmp/tensorboard\")\n\n# Run the operations to be profiled\nkey = jax.random.key(0)\nx = jax.random.normal(key, (5000, 5000))\ny = x @ x\ny.block_until_ready()\n\njax.profiler.stop_trace() \n```", "```py\nimport jax\n\nwith jax.profiler.trace(\"/tmp/tensorboard\"):\n  key = jax.random.key(0)\n  x = jax.random.normal(key, (5000, 5000))\n  y = x @ x\n  y.block_until_ready() \n```", "```py\n$  tensorboard  --logdir=/tmp/tensorboard\n[...]\nServing  TensorBoard  on  localhost;  to  expose  to  the  network,  use  a  proxy  or  pass  --bind_all\nTensorBoard  2.5.0  at  http://localhost:6006/  (Press  CTRL+C  to  quit) \n```", "```py\n    tensorboard  --logdir  /tmp/tensorboard/ \n    ```", "```py\n    import jax.profiler\n    jax.profiler.start_server(9999) \n    ```", "```py\nW external/org_tensorflow/tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcupti.so.10.1'; dlerror: libcupti.so.10.1: cannot open shared object file: No such file or directory\n2020-06-12 13:19:59.822799: E external/org_tensorflow/tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1422] function cupti_interface_->Subscribe( &subscriber_, (CUpti_CallbackFunc)ApiCallback, this)failed with error CUPTI could not be loaded or symbol could not be found. \n```", "```py\nexport  LD_LIBRARY_PATH=/usr/local/cuda-10.1/extras/CUPTI/lib64/:$LD_LIBRARY_PATH \n```", "```py\nE  external/org_tensorflow/tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1445]  function  cupti_interface_->EnableCallback(  0  ,  subscriber_,  CUPTI_CB_DOMAIN_DRIVER_API,  cbid)failed  with  error  CUPTI_ERROR_INSUFFICIENT_PRIVILEGES\n2020-06-12  14:31:54.097791:  E  external/org_tensorflow/tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1487]  function  cupti_interface_->ActivityDisable(activity)failed  with  error  CUPTI_ERROR_NOT_INITIALIZED \n```", "```py\necho  'options nvidia \"NVreg_RestrictProfilingToAdminUsers=0\"'  |  sudo  tee  -a  /etc/modprobe.d/nvidia-kernel-common.conf\nsudo  update-initramfs  -u\nsudo  reboot  now \n```", "```py\nssh  -L  6006:localhost:6006  <remote  server  address> \n```", "```py\n$  gcloud  compute  ssh  <machine-name>  --  -L  6006:localhost:6006 \n```", "```py\npip  uninstall  tensorflow  tf-nightly  tensorboard  tb-nightly\npip  install  tensorflow \n```"]